version: '3.7'
services:
    server:
      image: nginx:1.15-alpine
      restart: unless-stopped
      ports:
        - '8080:8080'
        - '9090:9090'
        - '18080:80'
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./certs:/opt/certs
        - ./data:/www/data

